name: "Build kt-time-traveler libraries"

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  build-core:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests with Gradle
      run: ./gradlew :kt-time-traveler-core:test
    - name: Build with Gradle
      run: ./gradlew :kt-time-traveler-core:build -x test

  build-spring-boot-starter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run tests with Gradle
        run: ./gradlew :kt-time-traveler-spring-boot-starter:test
      - name: Build with Gradle
        run: ./gradlew :kt-time-traveler-spring-boot-starter:build -x test

  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run tests with Gradle
        run: ./gradlew :kt-time-traveler-test:test
      - name: Build with Gradle
        run: ./gradlew :kt-time-traveler-test:build -x test
