name: Publish packages to GitHub Packages Registry
on:
  push:
    branches:
      - master
    paths:
      - 'kt-time-traveler-core/**'
      - 'kt-time-traveler-spring-boot-starter/**'
      - 'kt-time-traveler-spring-boot-test/**'
      - '**.gradle.kts'
      - '!.github/**'
      - '!README.md'
jobs:
  publish-core:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish package
        run: ./gradlew :kt-time-traveler-core:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-spring-boot-starter:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish package
        run: ./gradlew :kt-time-traveler-spring-boot-starter:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish package
        run: ./gradlew :kt-time-traveler-test:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}